server:
  port: 10011

spring:
  application:
    name: eurekaserver
  security:
    user:
      name: esha
      password: 123456
eureka:
  instance:
    hostname: eurekaserverha
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://es:123456@eurekaserver:10010/eureka/
