server:
  port: 10011
spring:
  application:
    name: eurekaclient
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka