server:
  port: 10010

spring:
  application:
    name: eurekaserver
  security:
    user:
      name: es
      password: 123456
eureka:
  instance:
    hostname: eurekaserver
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://esha:123456@eurekaserverha:10011/eureka/
